### ISSUE TITLE
app-accessibility/onboard can cause a segmentation fault

### ISSUE THREAD

**Issue by hoshino873** [hoshino873/gentoo-mint#1]
# Overview
`app-accessibility/onboard` with `Python 3.12` can cause a segmentation fault

# Details
I have confirmed that using `app-accessibility/onboard` with `dev-lang/python-3.12.3-r1` causes a segmentation fault when the mouse cursor focuses on its window. I am currently investigating potential workarounds or fixes for this issue.

Here is the backtrace I got when this issue was caused:
```
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007ffff79e4bd8 in _PyInterpreterState_GET () at ./Include/internal/pycore_pystate.h:133
133         return tstate->interp;
(gdb) bt
#0  0x00007ffff79e4bd8 in _PyInterpreterState_GET () at ./Include/internal/pycore_pystate.h:133
#1  0x00007ffff79e63ee in get_state () at Objects/obmalloc.c:866
#2  0x00007ffff79e757a in _PyObject_Malloc (ctx=0x0, nbytes=112) at Objects/obmalloc.c:1563
#3  0x00007ffff79e629a in PyObject_Malloc (size=112) at Objects/obmalloc.c:801
#4  0x00007ffff79e02b0 in _PyObject_New (tp=0x7ffff3d43c00 <osk_device_event_type>) at Objects/object.c:319
#5  0x00007ffff3d33ce6 in new_device_event () at Onboard/osk/osk_devices.c:100
#6  0x00007ffff3d349da in osk_devices_call_event_handler_pointer
    (dev=0x7ffff16cf5a0, type=7, display=0x5555557b93a0, xid_event=2097155, device_id=2, source_id=8, x=320, y=0, x_root=659, y_root=503, button=0, state=0, sequence=0, time=117308980) at Onboard/osk/osk_devices.c:452
#7  0x00007ffff3d3531c in handle_enter_event (evtype=7, xievent=0x555555d93a00, dev=0x7ffff16cf5a0) at Onboard/osk/osk_devices.c:779
#8  0x00007ffff3d353c1 in osk_devices_event_filter (gdk_xevent=0x7fffffff6b10, gdk_event=0x555555be15a0, dev=0x7ffff16cf5a0)
    at Onboard/osk/osk_devices.c:817
...
```

# Affected versions
- [~app-accessibility/onboard-1.4.1-r230401~](https://github.com/hoshino873/gentoo-mint/blob/main/app-accessibility/onboard/onboard-1.4.1-r230401.ebuild)
- [~app-accessibility/onboard-1.4.1-r240401~](https://github.com/hoshino873/gentoo-mint/blob/main/app-accessibility/onboard/onboard-1.4.1-r240401.ebuild)

# Links relating to this issue
- https://bugs.launchpad.net/ubuntu/+source/onboard/+bug/2064775
- https://bugs.launchpad.net/ubuntu/+source/onboard/+bug/2063041

**Comment by hoshino873** [comment]
Fix: 52494dadf9d82f9f100c0a4c72cb73745ef28700 ([patch](https://github.com/hoshino873/gentoo-mint/commit/52494dadf9d82f9f100c0a4c72cb73745ef28700#diff-0078a977ce8ad386eb6945ad4704306ebd68b407099d8253f91dc8191e420746))
